### ISSUE TITLE
ID niet nodig, combinatie van artikel_is en auteur_id uis de UNIQUE KEY

### ISSUE THREAD

**Issue by zwerver** [vincentlemstra/educom_wiki#2]
https://github.com/vincentlemstra/educom_wiki/blob/710323888a60f4ab490592c7caf22519a3cbc53c/project_inventarisatie/0.3_realisatie.sql#L47

**Comment by vincentlemstra** [comment]
- Removed id (primary key) 
- Added primary key with author_id and article_id
    - CONSTRAINT rating_pk PRIMARY KEY (author_id, article_id),
