### ISSUE TITLE
Unique key toevoegen

### ISSUE THREAD

**Issue by zwerver** [vincentlemstra/educom_wiki#3]
https://github.com/vincentlemstra/educom_wiki/blob/710323888a60f4ab490592c7caf22519a3cbc53c/project_inventarisatie/0.3_realisatie.sql#L41

De combinatie van tag_id en artikel_id is hier de key

**Comment by vincentlemstra** [comment]
Added primary key with article_id and tag_id:
    - CONSTRAINT article_tag_pk PRIMARY KEY (article_id, tag_id),
